#!/usr/bin/env python3
"""Generate UZC V2 MP3 slot + PCM reference for sintest_i2s_mp3."""

import math
import struct
from pathlib import Path

import lameenc

SR = 44100
FREQ = 441.0
PCM_SAMPLES = 576  # one MP3 granule — LAME output is 2 frames (~835 B)
UZC_PERIOD_STEREO = 1152
LEVEL = 12000
MAX_FRAME_SIZE = 896


def gen_pcm_mono() -> list[int]:
    pcm = []
    phase = 0.0
    for _ in range(PCM_SAMPLES):
        pcm.append(int(math.sin(2.0 * math.pi * phase) * LEVEL))
        phase += FREQ / SR
        if phase >= 1.0:
            phase -= 1.0
    return pcm


def encode_mp3(pcm_bytes: bytes) -> bytes:
    enc = lameenc.Encoder()
    enc.set_bit_rate(128)
    enc.set_in_sample_rate(SR)
    enc.set_channels(1)
    enc.set_quality(2)
    mp3 = enc.encode(pcm_bytes)
    mp3 += enc.flush()
    if not mp3 or mp3[0] != 0xFF or (mp3[1] & 0xE0) != 0xE0:
        raise RuntimeError("MP3 sync word missing")
    return mp3


def build_slot_v2(payload: bytes) -> bytes:
    real = len(payload)
    if real > MAX_FRAME_SIZE:
        raise RuntimeError(f"MP3 payload {real} exceeds MAX_FRAME_SIZE {MAX_FRAME_SIZE}")
    slot = bytearray(MAX_FRAME_SIZE + 4)
    struct.pack_into("<H", slot, 0, MAX_FRAME_SIZE)
    struct.pack_into("<H", slot, 2, real)
    slot[4 : 4 + real] = payload
    return bytes(slot[: MAX_FRAME_SIZE + 4])


def bytes_to_i16_words(data: bytes) -> list[int]:
    words = []
    for i in range(0, len(data), 2):
        lo = data[i]
        hi = data[i + 1] if i + 1 < len(data) else 0
        val = lo | (hi << 8)
        if val >= 0x8000:
            val -= 0x10000
        words.append(val)
    return words


def emit_slot_header(slot: bytes, out_path: Path) -> None:
    words = bytes_to_i16_words(slot)
    real = struct.unpack_from("<H", slot, 2)[0]
    lines = [
        "// Auto-generated by tools/gen_mp3_slot.py — do not edit",
        "#pragma once",
        "#include <stdint.h>",
        "",
        f"#define UZC_MP3_MAX_FRAME_SIZE   {MAX_FRAME_SIZE}u",
        f"#define UZC_MP3_REAL_FRAME_SIZE  {real}u",
        f"#define UZC_MP3_SLOT_BYTES       {len(slot)}u",
        f"#define UZC_MP3_SLOT_WORDS       {len(words)}u",
        f"#define UZC_MP3_PERIOD_STEREO    {UZC_PERIOD_STEREO}u",
        "",
        "static const int16_t kUzcMp3SlotWords[UZC_MP3_SLOT_WORDS] = {",
    ]
    for i in range(0, len(words), 8):
        chunk = words[i : i + 8]
        lines.append("  " + ", ".join(str(w) for w in chunk) + ",")
    lines.append("};")
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {out_path}  realMp3={real} slotWords={len(words)}")


def emit_ref_header(pcm: list[int], out_path: Path) -> None:
    lines = [
        "// Auto-generated source PCM (pre-MP3 encode)",
        "#pragma once",
        "#include <stdint.h>",
        "",
        f"#define UZC_MP3_PCM_REF_SAMPLES  {len(pcm)}u",
        "",
        "static const int16_t kUzcMp3PcmRef[UZC_MP3_PCM_REF_SAMPLES] = {",
    ]
    for i in range(0, len(pcm), 8):
        chunk = pcm[i : i + 8]
        lines.append("  " + ", ".join(str(v) for v in chunk) + ",")
    lines.append("};")
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {out_path}")


def main() -> None:
    root = Path(__file__).resolve().parent.parent
    pcm = gen_pcm_mono()
    pcm_bytes = struct.pack("<" + "h" * PCM_SAMPLES, *pcm)
    mp3 = encode_mp3(pcm_bytes)
    slot = build_slot_v2(mp3)
    emit_slot_header(slot, root / "master" / "src" / "uzc_mp3_slot.h")
    emit_ref_header(pcm, root / "slave" / "src" / "uzc_mp3_pcm_ref.h")


if __name__ == "__main__":
    main()
