#!/usr/bin/env python3
"""Generate UZC V2 MP3 slot + source PCM reference for mp3test."""

import math
import struct
from pathlib import Path

import lameenc

SR = 44100
FREQ = 441.0
PCM_SAMPLES = 576  # one MP3 granule — single frame in 512B slot decodes cleanly
UZC_PERIOD_STEREO = 1152  # production I2S period; playback loops decoded region
LEVEL = 12000
MAX_FRAME_SIZE = 896  # mp3test: holds full lame output (2 frames for 576-sample encode)


def gen_pcm_mono() -> list[int]:
    pcm = []
    phase = 0.0
    for _ in range(PCM_SAMPLES):
        pcm.append(int(math.sin(2.0 * math.pi * phase) * LEVEL))
        phase += FREQ / SR
        if phase >= 1.0:
            phase -= 1.0
    return pcm


def encode_mp3(pcm_bytes: bytes) -> bytes:
    enc = lameenc.Encoder()
    enc.set_bit_rate(128)
    enc.set_in_sample_rate(SR)
    enc.set_channels(1)
    enc.set_quality(2)
    mp3 = enc.encode(pcm_bytes)
    mp3 += enc.flush()
    if not mp3 or mp3[0] != 0xFF or (mp3[1] & 0xE0) != 0xE0:
        raise RuntimeError("MP3 sync word missing")
    return mp3


def mp3_frame_byte_length(h: bytes) -> int:
    if len(h) < 4 or h[0] != 0xFF or (h[1] & 0xE0) != 0xE0:
        return 0
    mpeg1 = ((h[1] >> 3) & 3) == 3
    br_idx = (h[2] >> 4) & 0x0F
    sr_idx = (h[2] >> 2) & 3
    br_kbps = [0, 32, 40, 48, 56, 64, 80, 96, 112, 128, 160, 192, 224, 256, 320, 0]
    sr_mpeg1 = [44100, 48000, 32000, 0]
    sr_mpeg2 = [22050, 24000, 16000, 0]
    if br_idx == 0 or br_idx == 0x0F or sr_idx == 3:
        return 0
    bitrate = br_kbps[br_idx] * 1000
    samplerate = sr_mpeg1[sr_idx] if mpeg1 else sr_mpeg2[sr_idx]
    if bitrate == 0 or samplerate == 0:
        return 0
    padding = (h[2] >> 1) & 1
    numerator = 144 * bitrate if mpeg1 else 72 * bitrate
    frame_len = (numerator // samplerate) + padding
    if frame_len < 4 or frame_len > 4096:
        return 0
    return frame_len


def first_mp3_frame(mp3: bytes) -> bytes:
    flen = mp3_frame_byte_length(mp3)
    if flen <= 0 or len(mp3) < flen:
        raise RuntimeError("Could not parse first MP3 frame")
    return mp3[:flen]


def build_slot_v2(payload: bytes) -> bytes:
    real = len(payload)
    if real > MAX_FRAME_SIZE:
        raise RuntimeError(f"MP3 payload {real} exceeds MAX_FRAME_SIZE {MAX_FRAME_SIZE}")
    slot = bytearray(MAX_FRAME_SIZE + 4)
    struct.pack_into("<H", slot, 0, MAX_FRAME_SIZE)
    struct.pack_into("<H", slot, 2, real)
    slot[4 : 4 + real] = payload
    return bytes(slot[: MAX_FRAME_SIZE + 4])


def bytes_to_i16_words(data: bytes) -> list[int]:
    words = []
    for i in range(0, len(data), 2):
        lo = data[i]
        hi = data[i + 1] if i + 1 < len(data) else 0
        val = lo | (hi << 8)
        if val >= 0x8000:
            val -= 0x10000
        words.append(val)
    return words


def emit_slot_header(slot: bytes, out_path: Path) -> None:
    words = bytes_to_i16_words(slot)
    real = struct.unpack_from("<H", slot, 2)[0]
    lines = [
        "// Auto-generated by tools/gen_mp3_slot.py",
        "#pragma once",
        "#include <stdint.h>",
        "",
        f"#define UZC_MP3_MAX_FRAME_SIZE   {MAX_FRAME_SIZE}u",
        f"#define UZC_MP3_REAL_FRAME_SIZE  {real}u",
        f"#define UZC_MP3_SLOT_BYTES       {len(slot)}u",
        f"#define UZC_MP3_SLOT_WORDS       {len(words)}u",
        f"#define UZC_MP3_PERIOD_STEREO    {UZC_PERIOD_STEREO}u",
        "",
        "static const int16_t kUzcMp3SlotWords[UZC_MP3_SLOT_WORDS] = {",
    ]
    for i in range(0, len(words), 8):
        chunk = words[i : i + 8]
        lines.append("  " + ", ".join(str(w) for w in chunk) + ",")
    lines.append("};")
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {out_path}  realMp3={real}")


def emit_ref_header(pcm: list[int], out_path: Path) -> None:
    lines = [
        "// Auto-generated source PCM (pre-MP3 encode) for DUMP/CMPREF",
        "#pragma once",
        "#include <stdint.h>",
        "",
        f"#define UZC_MP3_PCM_REF_SAMPLES  {len(pcm)}u",
        "",
        "static const int16_t kUzcMp3PcmRef[UZC_MP3_PCM_REF_SAMPLES] = {",
    ]
    for i in range(0, len(pcm), 8):
        chunk = pcm[i : i + 8]
        lines.append("  " + ", ".join(str(v) for v in chunk) + ",")
    lines.append("};")
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {out_path}")


def main() -> None:
    src = Path(__file__).resolve().parent.parent / "src"
    pcm = gen_pcm_mono()
    pcm_bytes = struct.pack("<" + "h" * PCM_SAMPLES, *pcm)
    mp3 = encode_mp3(pcm_bytes)
    slot = build_slot_v2(mp3)
    emit_slot_header(slot, src / "uzc_mp3_slot.h")
    emit_ref_header(pcm, src / "uzc_mp3_pcm_ref.h")


if __name__ == "__main__":
    main()
